blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    # /blog/
    url(r'^$', views.blog,name='blog'),
]

contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns =[
    url(r'^$',views.contact,name='contact'),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # /home/
    url(r'^$', views.index,name='index'),
]

personalprofile/urls.py
from django.conf.urls import url
from . import views

app_name = 'personalprofile'

urlpatterns =[
# /profile/
    url(r'^$', views.profile,name='profile'),
]

personalwebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^profile/', include('personalprofile.urls')),
    url(r'^resume/', include('resume.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^home/$', views.home),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import url
from . import views


app_name = 'portfolio'

urlpatterns = [
    url(r'^$',views.portfolio,name='portfolio'),
]

posts/urls.py
from django.conf.urls import url
from  . import views
app_name='posts'

urlpatterns=[
    url(r'^$',views.posts,name='posts'),
]

resume/urls.py
from django.conf.urls import url
from . import views

app_name = 'resume'

urlpatterns = [
    url(r'^$', views.resume, name='resume'),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

contact/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/models.py
from django.db import models
# Create your models here.

class PersonalInfo(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=500)
    photo = models.FileField()

    def __str__(self):
        return self.name

personalprofile/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

posts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

resume/models.py
from django.db import models

# Create your models here.

blog/views.py
from  django.shortcuts import render
# Create your views here.

def blog(request):
    return render(request,'blog.html')

contact/views.py
from django.shortcuts import render
from home.models import PersonalInfo
# Create your views here.
def contact(request):
    userinfo = PersonalInfo.objects.all();
    return render(request,'contact.html',{'userinfo':userinfo})

home/views.py
from  django.shortcuts import render
from  django.http import HttpResponseRedirect
from .models import PersonalInfo
# Create your views here.

def index(request):
    userinfo = PersonalInfo.objects.all();
    return render(request,'index.html',{'userinfo':userinfo})

def home(request):
    return HttpResponseRedirect('/')

personalprofile/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request,'profile.html')

portfolio/views.py
from django.shortcuts import render

# Create your views here.

def portfolio(request):
    return render(request,'portfolio.html')

posts/views.py
from django.shortcuts import render

# Create your views here.
def posts(request):
    return render(request, 'post-img.html')

resume/views.py
from django.shortcuts import render
from home.models import PersonalInfo
# Create your views here.
def resume(request):
    userinfo = PersonalInfo.objects.all();
    return render(request,'resume.html',{'userinfo':userinfo})

contact/templates/contact.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7 ]>
<html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>
<html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>
<html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en"> <!--<![endif]-->


<head>
    <meta charset="utf-8"/>
    <title>Contact</title>
    <meta name="author" content="xalien"/>
    <meta name="keywords" content="django, css3, template, html5 template"/>
    <meta name="description" content="Personal Vcard & Resume HTML Template"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <!-- Font Awesome -->
    <link type="text/css" media="all" href="{% static '/assets/fonts/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"/>
    <!-- Libs CSS -->
    <link type="text/css" media="all" href="{% static '/assets/boostrap-files/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <!-- Animate CSS -->
    <link type="text/css" media="all" href="{% static '/assets/css/animate.css' %}" rel="stylesheet"/>
    <!-- Template CSS -->
    <link type="text/css" media="all" href="{% static '/assets/css/contact.form.css' %}" rel="stylesheet"/>
    <link type="text/css" media="all" href="{% static '/assets/css/style.css' %}" rel="stylesheet"/>
    <!-- Switcher CSS -->
    <link href="{% static 'assets/css/colour-scheme/color-blue.css' %}" rel="stylesheet" type="text/css" data-color="color-blue"
          media="all" id="stylesheet-new">
    <!-- Responsive CSS -->
    <link type="text/css" media="all" href="{% static '/assets/css/respons.css' %}" rel="stylesheet"/>
    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="144x144" href="{% static '/assets/img/favicons/apple-touch-icon-144x144.png' %}"/>
    <link rel="apple-touch-icon" sizes="114x114" href="{% static '/assets/img/favicons/apple-touch-icon-114x114.png' %}"/>
    <link rel="apple-touch-icon" sizes="72x72" href="{% static '/assets/img/favicons/apple-touch-icon-72x72.png' %}"/>
    <link rel="apple-touch-icon" href="{% static '/assets/img/favicons/apple-touch-icon.png' %}"/>
    <link rel="shortcut icon" href="{% static '/assets/img/favicons/favicon.png' %}"/>
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,100italic,200,200italic,300,300italic,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic'
          rel='stylesheet' type='text/css'>

</head>
<body>

<!-- Load page -->
<div class="animationload">
    <div class="loader"></div>
</div>
<!-- End load page -->

<div id="wraper">
{%for userinfo in userinfo%}
    <!-- Start Head section -->
    <header class="head">
        <!-- start container -->
        <div class="container">
            <!-- start row -->
            <div class="row">
                <div class="col-xs-8 col-sm-11 col-lg-11">
                    <img class="logo-page" src="{% static '/assets/img/contact_l.png' %}" alt="Ukieweb">
                    <!-- Title Page -->
                    <h2 class="title">Contact</h2>
                    <!-- Description Page -->
                    <h4 class="sub-title">Get in touch with me</h4>
                </div>
                <div class="col-xs-4 col-sm-1 col-lg-1 text-right">
                    <a href="{% url 'home:index' %}" class="btn-close hover-animate"></a>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </header>
    <!-- End Head section -->

    <!-- Start Content section -->
    <section class="content padding-block border-bottom">
        <!-- start container -->
        <div class="container">
            <!-- start row -->
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-lg-6 padding-bottom">
                    <h3 class="title title-contact">Contact info</h3>
                    <div class="block-grey">
                        <table>
                            <tr>
                                <td class="font-weight-m width-td">Address</td>
                                <td>{{ userinfo.address }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-m">Phone</td>
                                <td><a href="tel:3801234567890">{{ userinfo.phone }}</a></td>
                            </tr>
                            <tr>
                                <td class="font-weight-m">E-mail</td>
                                <td><a href="mailto:info@yourdomain.com">{{userinfo.email}}</a></td>
                            </tr>
                            <tr>
                                <td class="font-weight-m">Skype</td>
                                <td>jonh_doe</td>
                            </tr>
                            <tr>
                                <td class="font-weight-m">Website</td>
                                <td><a href="{% url 'home:index' %}">www.iamxalien.com</a></td>
                            </tr>
                        </table>
                        <!-- social icon -->
                        <div class="social">
                            <ul class="animated" data-animation="fadeIn" data-animation-delay="600">
                                <!-- social icons -->
                                <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-google-plus"></i></a>
                                </li>
                                <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-youtube"></i></a></li>
                                <!--
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-behance"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-pinterest"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-digg"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-deviantart"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-envelope-square"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-delicious"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-instagram"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-dropbox"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-skype"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-tumblr"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-vimeo-square"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-flickr"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-github-alt"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-renren"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-vk"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-xing"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-weibo"></i></a></li>
                                    <li><a class="ukie-icons hover-animate" href="#"><i class="fa fa-rss"></i></a></li>
                                -->
                            </ul>
                        </div>
                        <!-- end social icon -->
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-lg-6">
                    <h3 class="title title-contact">Contact form</h3>
                    <!-- Start Contact Form -->
                    <div class="contact-form">
                        <form action="https://ukieweb.com/envato/ukiecard/style2/assets/php/contact.php" id="contact-form" method="post">
                            <input type="text" id="user-name" name="user-name" value="" placeholder="Name"/>
                            <input type="email" id="user-email" name="user-email" value="" placeholder="Email"/>
                            <input type="hidden" id="user-status" name="user-status" value="1"/>
                            <textarea id="user-message" name="user-message" placeholder="Message"></textarea>
                            <div class="footer-form">
                                <input type="submit" id="submit-btn" class="btn btn-color hover-animate"
                                       value="Send Message"/>
                                <div class="info-message-form">
                                    <p>Please fill out all the fields!</p>
                                    <span class="close-msg"><i class="fa fa-close"></i></span>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- End Contact Form -->
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </section>
    <!-- End Content section -->

    <!-- Start Map section -->
    <div class="contact-map padding-block text-center">
        <!-- start container -->
        <div class="container">
            <!-- start row -->
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-lg-12">
                    <div id="map" class="map"></div>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- End Map section -->

    <!-- Start Footer section -->
    <footer class="footer">
        <!-- start container -->
        <div class="container">
            <!-- start row -->
            <div class="row">
                <!-- start phone number -->
                <div class="col-xs-12 col-sm-6 col-lg-3">
                    <a href="#" class="hover-animate">
                        <span class="ukie-icons hover-animate"><i class="fa fa-phone"></i></span> {{ userinfo.phone }}
                    </a>
                </div>
                <!-- end phone number -->
                <!-- start email -->
                <div class="col-xs-12 col-sm-6 col-lg-3">
                    <a href="#" class="hover-animate">
                        <span class="ukie-icons hover-animate"><i class="fa fa-paper-plane"></i></span>
                        {{ userinfo.email }}
                    </a>
                </div>
                <!-- end email -->
                <!-- start address -->
                <div class="col-xs-12 col-sm-6 col-lg-3">
                    <a href="#" class="hover-animate">
                        <span class="ukie-icons hover-animate"><i class="fa fa-map-marker"></i></span>{{ userinfo.address }}
                    </a>
                </div>
                <!-- end address -->
                <!-- start Copyright -->
                <div class="col-xs-12 col-sm-6 col-lg-3 text-right">
                    <span class="copyright">Copyright © 2016 All right reserved</span>
                </div>
                <!-- end Copyright -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </footer>
    <!-- End Footer section -->

</div>

<!-- Scroll to Top -->
<a href="#" class="btn hover-animate scrollToTop"><i class="fa fa-angle-up"></i></a>
<!-- End Scroll to Top -->

<!-- Scripts -->
<script src="{% static '/assets/js/jquery-1.11.2.min.js' %}" type="text/javascript"></script>
<script src="{% static '/assets/boostrap-files/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static '/assets/js/jquery.appear.js' %}" type="text/javascript"></script>
<script src="{% static '/assets/js/jquery.mixitup.min.js' %}" type="text/javascript"></script>
<script src="{% static '/assets/js/owl.carousel.min.js' %}" type="text/javascript"></script>
<script src="{% static '/assets/js/jquery.flexslider-min.js' %}" type="text/javascript"></script>
<script src="{% static '/assets/js/jquery.inview.min.js' %}" type="text/javascript"></script>
<script src="{% static '/assets/js/jquery.knob.min.js' %}" type="text/javascript"></script>
<script src="{% static '/assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
<script src="{% static '/assets/js/jquery.ratyli.js' %}" type="text/javascript"></script>
<script src="{% static '/assets/js/contact_scripts.js' %}" type="text/javascript"></script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAAo2IL5DSk5Moz71RjBlCPnJXodFb4208&amp;callback=initMap">
</script>
<script src="{% static '/assets/js/scripts.js' %}" type="text/javascript"></script>
{% endfor %}
</body>
</html>